### ISSUE TITLE
Nuget package target paths fail on linux

### ISSUE THREAD

**Issue by jonnymuir** [thepensionsregulator/govuk-frontend-aspnetcore-extensions#240]
I am adding the project to an umbraco project using:

```
dotnet add package ThePensionsRegulator.GovUk.Frontend.Umbraco
```

When I run the project using 
```
dotnet run
```

I get an error
```
Building...
/root/.nuget/packages/thepensionsregulator.govuk.frontend.umbraco/5.0.0/buildTransitive/ThePensionsRegulator.GovUk.Frontend.Umbraco.targets(54,3): error MSB3733: Input file "/.nuget/packages/thepensionsregulator.govuk.frontend.umbraco/5.0.0/thepensionsregulator.govuk.frontend.umbraco.nuspec" cannot be opened. Could not find a part of the path '/.nuget/packages/thepensionsregulator.govuk.frontend.umbraco/5.0.0/thepensionsregulator.govuk.frontend.umbraco.nuspec'. [/root/dev/mermaid-workflow/mermaid-cms/mermaid-cms.csproj]

The build failed. Fix the build errors and run again.
```

The reason for the is the use of `$(UserProfile)` in the ThePensionsRegulator.GovUk.Frontend.Umbraco.targets file. This is, as far as I am aware, only set on windows machines. Linux uses `$(HOME)`

To fix it you can add:

```
<PropertyGroup>
  <UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</UserProfile>
  <UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</UserProfile>
</PropertyGroup>
```

Near the top of the target file.

If anyone else gets this and needs a work round you can also add this in the PropertyGroup section of your csproj file

```
    <UserProfile Condition="'$(UserProfile)' == ''">$(HOME)</UserProfile>
```

PS - this is an awesome project. I will try and get round to contributing and providing a pull request for this, but I need a little time to get my head round it all. Also I did a quick search in the repo and the change may be required for the other nuget targets?

**Comment by sussexrick** [comment]
Hi @jonnymoo, thank you for logging this and for being our first external user (that we know of)!

Official Linux support isn't on our roadmap, but we'd be happy to accept a PR for a non-breaking change to enable it unofficially. I've checked on my local Windows development environment and our build environment and both have the `OS` environment variable set to `Windows_NT` so it shouldn't break anything for our Windows development.

**Comment by jonnymuir** [comment]
Ha - absolute pleasure to be your first external user, surprised  - this is a cracking wrap around the GDS toolkit for Umbraco. 

You'll be glad to know that apart from that it is working perfectly (so far), so you could save your self a few pennies and choose linux as your platform when deploying to cloud ;) I'm running it on umbraco 12 which seems to behaves very nicely too.
